### ISSUE TITLE
G2Plot  对比漏斗图

### ISSUE THREAD

**Issue by XuHatcher** [antvis/G2Plot#1153]
G2Plot能像G2的漏斗图一样，左右的数值进行区分吗？而不是左右的数值都是同样的。

**Comment by 13kay** [comment]
同问，label显示的数值为两边之和，其实应该分别显示对比值才对
![funnel](https://user-images.githubusercontent.com/394134/89013909-4f03a880-d347-11ea-945b-ddd6f5dfafaa.png)

**Comment by tingkai-zhang** [comment]
- [x] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6e936)

### Steps to reproduce
In the demo, the numerical value for comparison shows the sum of both. 
What I expect is the number on each side shows its individual value.

| Environment | Info |
|---|---|
| g2plot | 1.1.18 |
| System | Ubuntu 20.04 LTS |
| Browser | Chrome Version 84.0.4147.105 (64-bit) |

---
I couldn't find any configuration for that field. I am not sure its due to missing documentation or its a bug. Hopefully we will have a quick feedback. Thank you!

**Comment by tingkai-zhang** [comment]
Ask for attention 
@lxfu1 
@paleface001
@zqlu

Let me know if I can provide more information. Thanks!

**Comment by hustcc** [comment]
v1 不再处理， v2 中 @liuzhenying 考虑掉这些诉求！
