### ISSUE TITLE
🐛 [BUG] Legend label does not get the right color

### ISSUE THREAD

**Issue by calebeaires** [antvis/G2Plot#3083]
### 🐛 Bug description [Please make everyone to understand it]
label legend from Pie charts  does not get the custom color

### 📷 Step to reproduce
Create a simple PIE, no custom settings but change the legend color.

### 🏞 Expected result
Legend Label color in red

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:  "@antv/g2plot": "^2.4.7",
* **Platform**: macos
![CleanShot 2022-01-20 at 12 11 28@2x](https://user-images.githubusercontent.com/794195/150366330-92810f01-66f9-49a8-b869-75853c81ac40.png)

**Comment by connono** [comment]
use item name  instead of label.
<img width="1214" alt="3083-1" src="https://user-images.githubusercontent.com/36756846/150489257-7c6ede60-e638-452a-9259-bbfd7518d05a.png">
<img width="1224" alt="3083-2" src="https://user-images.githubusercontent.com/36756846/150489390-9bdb9e4d-b0c7-4e63-8424-a5b6d595261d.png">
remember use style after legend.
<img width="995" alt="3083-3" src="https://user-images.githubusercontent.com/36756846/150489691-f1e4e1f5-aa3f-46b2-b307-76101ceaa7a7.png">
